apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-c
  description: Team C Group
spec:
  type: department
  # Intentional no profile for testing
  parent: demo-corp
  children: [development]