name: E2E Linux MySQL
on:
  # NOTE: If you change these you must update verify_e2e-linux-noop.yml as well
  pull_request:
    paths-ignore:
      - '.changeset/**'
      - 'contrib/**'
      - 'docs/**'
      - 'microsite/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql8:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306/tcp

    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    name: E2E Linux mysql ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'GitHub e2e user'
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
          cache: ''
      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}-${{ github.ref }}

      - run: yarn tsc
      - run: yarn backstage-cli repo build
      - name: run E2E test
        run: |
          yarn e2e-test run --dbms=mysql
        env:
          BACKSTAGE_TEST_DISABLE_DOCKER: 1
          BACKSTAGE_TEST_DATABASE_MYSQL8_CONNECTION_STRING: mysql://root:root@localhost:${{ job.services.mysql8.ports[3306] }}/ignored
